default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['POSTGRES_HOST'] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  timeout: 5000

development:
  <<: *default
  database: authentication_without_gem_development

test:
  <<: *default
  database: authentication_without_gem_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  <<: *default
  database: authentication_without_gem_production